# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('root', models.IntegerField(help_text='requirement root id')),
                ('pre', models.IntegerField(help_text='requirement pre id')),
                ('status', models.IntegerField(help_text='状态用数字表示')),
                ('extend1', models.CharField(blank=True, help_text='备用1', max_length=50, null=True)),
                ('extend2', models.CharField(blank=True, help_text='备用2', max_length=50, null=True)),
                ('extend3', models.CharField(blank=True, help_text='备用3', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '需求表',
                'verbose_name_plural': '需求表',
                'db_table': 'requirement2',
            },
        ),
        migrations.CreateModel(
            name='scriptVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('doc', models.FileField(upload_to='./upload/yxtest3/scriptVersion')),
                ('creator', models.CharField(help_text='负责人', max_length=20)),
                ('time', models.DateTimeField()),
                ('remarks', models.CharField(help_text='备注内容', max_length=200)),
                ('extend1', models.CharField(blank=True, help_text='备用1', max_length=50, null=True)),
                ('extend2', models.CharField(blank=True, help_text='备用2', max_length=50, null=True)),
                ('extend3', models.CharField(blank=True, help_text='备用3', max_length=50, null=True)),
            ],
            options={
                'verbose_name': '脚本表',
                'verbose_name_plural': '脚本表',
                'db_table': 'scriptversion2',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('doc', models.FileField(upload_to='./upload/yxtest3/test')),
                ('creator', models.CharField(help_text='负责人', max_length=20)),
                ('time', models.DateTimeField()),
                ('status', models.IntegerField(help_text='状态用数字表示')),
                ('extend1', models.CharField(blank=True, help_text='备用1', max_length=50, null=True)),
                ('extend2', models.CharField(blank=True, help_text='备用2', max_length=50, null=True)),
                ('extend3', models.CharField(blank=True, help_text='备用3', max_length=50, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yxtest3.requirement')),
            ],
            options={
                'verbose_name': '测试表',
                'verbose_name_plural': '测试表',
                'db_table': 'testtable2',
            },
        ),
        migrations.AddField(
            model_name='scriptversion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yxtest3.test'),
        ),
    ]
